### ISSUE TITLE
Not working with latest version of Stretch

### ISSUE THREAD

**Issue by damonkh** [peebles/rpi3-wifi-station-ap-stretch#3]
Excellent solution, though it is having trouble with the latest version of Stretch on Raspberry Pi3.
My version:
`pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux`

Manually walking the steps I have only been able to get this to work twice before a reboot.
After reboot I am getting:

`pi@raspberrypi:~ $ sudo journalctl -xe
-- Subject: Unit dnsmasq.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit dnsmasq.service has begun starting up.
Mar 18 15:25:16 raspberrypi dnsmasq[2197]: dnsmasq: syntax check OK.
Mar 18 15:25:16 raspberrypi dnsmasq[2200]: dnsmasq: unknown interface uap0
Mar 18 15:25:16 raspberrypi dnsmasq[2200]: unknown interface uap0
Mar 18 15:25:16 raspberrypi dnsmasq[2200]: FAILED to start up
Mar 18 15:25:16 raspberrypi systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
Mar 18 15:25:16 raspberrypi systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
-- Subject: Unit dnsmasq.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit dnsmasq.service has failed.`

From what I am finding out, rc.local has issues and should avoid using that.  As well as ifup/ifdown.

Any suggestions?  Thanks a mil!

**Comment by suiluj** [comment]
I just installed the latest version of raspbian stretch lite and got it working without any problems.
My raspberry pi 3 version seems to be the same:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux
```


@damonkh Perhaps you can backup your sd card and try with a fresh clean raspbian install for minimal error sources.

I think it is a fantastic tutorial so thank you very much for your great work @peebles .

Edit: Yesterday i wrote in this post that wlan0 did not work after reboot.
That was because i made a stupid mistake an wrote the additional command in the `rc.local` file after exit 0. No surprise the commands were not executed. :D Now everything works perfect on my raspberrypi.
